print('Hello, World!')
print ('Hello')
print('I\'m studying Python') 
print()
print('and having fun!')
print('I\'m studying Python', 'and having fun!')
print('I\'m studying\nPython')
print('I\'m learning to become a Python developer!\nI\'m so excited!')